import { Image } from "@/api/generated";

export const MockCats: Image[] = [
  {
    breeds: [],
    id: "AEUsEzR7Z",
    url: "https://cdn2.thecatapi.com/images/AEUsEzR7Z.jpg",
    width: 735,
    height: 490,
  },
  {
    breeds: [
      {
        weight: {
          imperial: "8 - 16",
          metric: "4 - 7",
        },
        id: "cypr",
        name: "Cyprus",
        origin: "Cyprus",
        description:
          "Loving, loyal, social and inquisitive, the Cyprus cat forms strong ties with their families and love nothing more than to be involved in everything that goes on in their surroundings. They are not overly active by nature which makes them the perfect companion for people who would like to share their homes with a laid-back relaxed feline companion. ",
        life_span: "12 - 15",
        indoor: 0,
        alt_names: "Cypriot cat",
        adaptability: 5,
        affection_level: 5,
        child_friendly: 4,
        dog_friendly: 5,
        energy_level: 4,
        grooming: 3,
        health_issues: 1,
        intelligence: 3,
        shedding_level: 3,
        social_needs: 3,
        stranger_friendly: 4,
        vocalisation: 3,
        experimental: 0,
        hairless: 0,
        natural: 1,
        rare: 0,
        rex: 0,
        suppressed_tail: 0,
        short_legs: 0,
        wikipedia_url: "https://en.wikipedia.org/wiki/Cyprus_cat",
        hypoallergenic: 0,
        reference_image_id: "tJbzb7FKo",
      },
    ],
    id: "8cupXgk0j",
    url: "https://cdn2.thecatapi.com/images/8cupXgk0j.jpg",
    width: 3000,
    height: 2000,
  },
  {
    breeds: [],
    id: "lzMtOipwL",
    url: "https://cdn2.thecatapi.com/images/lzMtOipwL.jpg",
    width: 630,
    height: 360,
  },
  {
    breeds: [],
    id: "bKpyoUAvf",
    url: "https://cdn2.thecatapi.com/images/bKpyoUAvf.jpg",
    width: 299,
    height: 168,
  },
  {
    breeds: [],
    id: "7AewAINJ_",
    url: "https://cdn2.thecatapi.com/images/7AewAINJ_.jpg",
    width: 275,
    height: 183,
  },
  {
    breeds: [],
    id: "86fNLtAoW",
    url: "https://cdn2.thecatapi.com/images/86fNLtAoW.jpg",
    width: 299,
    height: 168,
  },
];
